// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMPqhzUYEK0dTLO4ut9aWZiE-H-b7JBT0',
    appId: '1:486756602066:web:4e5ad39f0875272418dd0b',
    messagingSenderId: '486756602066',
    projectId: 'rev-fb-2',
    authDomain: 'rev-fb-2.firebaseapp.com',
    storageBucket: 'rev-fb-2.appspot.com',
    measurementId: 'G-QD6T22MD1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdf_RGrkgJvURkp67oAXEz5ACHZLuKM4k',
    appId: '1:486756602066:android:725924cc2c0152ff18dd0b',
    messagingSenderId: '486756602066',
    projectId: 'rev-fb-2',
    storageBucket: 'rev-fb-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfYJrTMhZ97lq1jk3o2tBvfBk8v9uaeBE',
    appId: '1:486756602066:ios:65cdbd0594cdfdac18dd0b',
    messagingSenderId: '486756602066',
    projectId: 'rev-fb-2',
    storageBucket: 'rev-fb-2.appspot.com',
    iosBundleId: 'com.example.revFbApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfYJrTMhZ97lq1jk3o2tBvfBk8v9uaeBE',
    appId: '1:486756602066:ios:4402419c2ba61dcc18dd0b',
    messagingSenderId: '486756602066',
    projectId: 'rev-fb-2',
    storageBucket: 'rev-fb-2.appspot.com',
    iosBundleId: 'com.example.revFbApp.RunnerTests',
  );
}
